permissions:
  contents: write
on:
  push:
    branches:
      - master

jobs:
  ci:
    # Call the reusable ci.yml workflow in this repo
    uses: ./.github/workflows/ci.yml
    with:
      node-version: '18'
      package-manager: 'npm'
      install-command: 'npm install && npm install -g eas-cli'
      build-command: 'eas build --platform android --non-interactive --profile internal'
      use-expo: true
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download Artifacts
        uses: actions/download-artifact@v4
        with:
          workflow-run-id: ${{ github.run_id }}

      - name: ðŸ·ï¸ Get app version from app.json
        id: get_version
        run: echo "APP_VERSION=$(node -p 'require(\"./app.json\").expo.version')" >> $GITHUB_OUTPUT

      - name: ðŸ“¦ Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.APP_VERSION }}-${{ github.run_number }}
          name: Release v${{ steps.get_version.outputs.APP_VERSION }}-${{ github.run_number }}
          body: |
            Automated build: ${{ github.run_number }}.
            Profile: Internal Android
            Made by: M1778
          draft: false
          prerelease: false
          files: |
            build/internal/*.apk
